/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ApiKeyControllerGet200Response } from '../model';
// @ts-ignore
import { ApiKeyControllerGet200ResponseAllOfItemsInner } from '../model';
// @ts-ignore
import { ApiKeyCreateControllerArgs } from '../model';
// @ts-ignore
import { IdModel } from '../model';
// @ts-ignore
import { OneTimeApiKeyEntity } from '../model';
/**
 * ApiKeysApi - axios parameter creator
 * @export
 */
export const ApiKeysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ApiKeyCreateControllerArgs} apiKeyCreateControllerArgs 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerCreate: async (apiKeyCreateControllerArgs: ApiKeyCreateControllerArgs, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiKeyCreateControllerArgs' is not null or undefined
            assertParamExists('apiKeyControllerCreate', 'apiKeyCreateControllerArgs', apiKeyCreateControllerArgs)
            const localVarPath = `/api/api-keys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiKeyCreateControllerArgs, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiKeyControllerDelete', 'id', id)
            const localVarPath = `/api/api-keys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerFind: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiKeyControllerFind', 'id', id)
            const localVarPath = `/api/api-keys/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerGet: async (name?: string, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/api-keys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiKeysApi - functional programming interface
 * @export
 */
export const ApiKeysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiKeysApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ApiKeyCreateControllerArgs} apiKeyCreateControllerArgs 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiKeyControllerCreate(apiKeyCreateControllerArgs: ApiKeyCreateControllerArgs, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OneTimeApiKeyEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiKeyControllerCreate(apiKeyCreateControllerArgs, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiKeyControllerDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiKeyControllerDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiKeyControllerFind(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiKeyControllerGet200ResponseAllOfItemsInner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiKeyControllerFind(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} [name] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiKeyControllerGet(name?: string, page?: number, perPage?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiKeyControllerGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiKeyControllerGet(name, page, perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ApiKeysApi - factory interface
 * @export
 */
export const ApiKeysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiKeysApiFp(configuration)
    return {
        /**
         * 
         * @param {ApiKeysApiApiKeyControllerCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerCreate(requestParameters: ApiKeysApiApiKeyControllerCreateRequest, options?: AxiosRequestConfig): AxiosPromise<OneTimeApiKeyEntity> {
            return localVarFp.apiKeyControllerCreate(requestParameters.apiKeyCreateControllerArgs, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ApiKeysApiApiKeyControllerDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerDelete(requestParameters: ApiKeysApiApiKeyControllerDeleteRequest, options?: AxiosRequestConfig): AxiosPromise<IdModel> {
            return localVarFp.apiKeyControllerDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ApiKeysApiApiKeyControllerFindRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerFind(requestParameters: ApiKeysApiApiKeyControllerFindRequest, options?: AxiosRequestConfig): AxiosPromise<ApiKeyControllerGet200ResponseAllOfItemsInner> {
            return localVarFp.apiKeyControllerFind(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ApiKeysApiApiKeyControllerGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiKeyControllerGet(requestParameters: ApiKeysApiApiKeyControllerGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<ApiKeyControllerGet200Response> {
            return localVarFp.apiKeyControllerGet(requestParameters.name, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiKeyControllerCreate operation in ApiKeysApi.
 * @export
 * @interface ApiKeysApiApiKeyControllerCreateRequest
 */
export interface ApiKeysApiApiKeyControllerCreateRequest {
    /**
     * 
     * @type {ApiKeyCreateControllerArgs}
     * @memberof ApiKeysApiApiKeyControllerCreate
     */
    readonly apiKeyCreateControllerArgs: ApiKeyCreateControllerArgs
}

/**
 * Request parameters for apiKeyControllerDelete operation in ApiKeysApi.
 * @export
 * @interface ApiKeysApiApiKeyControllerDeleteRequest
 */
export interface ApiKeysApiApiKeyControllerDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiKeysApiApiKeyControllerDelete
     */
    readonly id: string
}

/**
 * Request parameters for apiKeyControllerFind operation in ApiKeysApi.
 * @export
 * @interface ApiKeysApiApiKeyControllerFindRequest
 */
export interface ApiKeysApiApiKeyControllerFindRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiKeysApiApiKeyControllerFind
     */
    readonly id: string
}

/**
 * Request parameters for apiKeyControllerGet operation in ApiKeysApi.
 * @export
 * @interface ApiKeysApiApiKeyControllerGetRequest
 */
export interface ApiKeysApiApiKeyControllerGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiKeysApiApiKeyControllerGet
     */
    readonly name?: string

    /**
     * 
     * @type {number}
     * @memberof ApiKeysApiApiKeyControllerGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof ApiKeysApiApiKeyControllerGet
     */
    readonly perPage?: number
}

/**
 * ApiKeysApi - object-oriented interface
 * @export
 * @class ApiKeysApi
 * @extends {BaseAPI}
 */
export class ApiKeysApi extends BaseAPI {
    /**
     * 
     * @param {ApiKeysApiApiKeyControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApi
     */
    public apiKeyControllerCreate(requestParameters: ApiKeysApiApiKeyControllerCreateRequest, options?: AxiosRequestConfig) {
        return ApiKeysApiFp(this.configuration).apiKeyControllerCreate(requestParameters.apiKeyCreateControllerArgs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ApiKeysApiApiKeyControllerDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApi
     */
    public apiKeyControllerDelete(requestParameters: ApiKeysApiApiKeyControllerDeleteRequest, options?: AxiosRequestConfig) {
        return ApiKeysApiFp(this.configuration).apiKeyControllerDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ApiKeysApiApiKeyControllerFindRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApi
     */
    public apiKeyControllerFind(requestParameters: ApiKeysApiApiKeyControllerFindRequest, options?: AxiosRequestConfig) {
        return ApiKeysApiFp(this.configuration).apiKeyControllerFind(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ApiKeysApiApiKeyControllerGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiKeysApi
     */
    public apiKeyControllerGet(requestParameters: ApiKeysApiApiKeyControllerGetRequest = {}, options?: AxiosRequestConfig) {
        return ApiKeysApiFp(this.configuration).apiKeyControllerGet(requestParameters.name, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }
}
