/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { IdModel } from '../model';
/**
 * QuickpayApi - axios parameter creator
 * @export
 */
export const QuickpayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} quickpayChecksumSha256 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quickpayWebhookControllerWebhook: async (quickpayChecksumSha256: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quickpayChecksumSha256' is not null or undefined
            assertParamExists('quickpayWebhookControllerWebhook', 'quickpayChecksumSha256', quickpayChecksumSha256)
            const localVarPath = `/api/webhooks/quickpay`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (quickpayChecksumSha256 != null) {
                localVarHeaderParameter['quickpay-checksum-sha256'] = String(quickpayChecksumSha256);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuickpayApi - functional programming interface
 * @export
 */
export const QuickpayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuickpayApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} quickpayChecksumSha256 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quickpayWebhookControllerWebhook(quickpayChecksumSha256: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quickpayWebhookControllerWebhook(quickpayChecksumSha256, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QuickpayApi - factory interface
 * @export
 */
export const QuickpayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuickpayApiFp(configuration)
    return {
        /**
         * 
         * @param {QuickpayApiQuickpayWebhookControllerWebhookRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quickpayWebhookControllerWebhook(requestParameters: QuickpayApiQuickpayWebhookControllerWebhookRequest, options?: AxiosRequestConfig): AxiosPromise<IdModel> {
            return localVarFp.quickpayWebhookControllerWebhook(requestParameters.quickpayChecksumSha256, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for quickpayWebhookControllerWebhook operation in QuickpayApi.
 * @export
 * @interface QuickpayApiQuickpayWebhookControllerWebhookRequest
 */
export interface QuickpayApiQuickpayWebhookControllerWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof QuickpayApiQuickpayWebhookControllerWebhook
     */
    readonly quickpayChecksumSha256: string
}

/**
 * QuickpayApi - object-oriented interface
 * @export
 * @class QuickpayApi
 * @extends {BaseAPI}
 */
export class QuickpayApi extends BaseAPI {
    /**
     * 
     * @param {QuickpayApiQuickpayWebhookControllerWebhookRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuickpayApi
     */
    public quickpayWebhookControllerWebhook(requestParameters: QuickpayApiQuickpayWebhookControllerWebhookRequest, options?: AxiosRequestConfig) {
        return QuickpayApiFp(this.configuration).quickpayWebhookControllerWebhook(requestParameters.quickpayChecksumSha256, options).then((request) => request(this.axios, this.basePath));
    }
}
