/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiKeyEntity
 */
export interface ApiKeyEntity {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyEntity
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyEntity
     */
    'modificationDate': string;
}

