/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiKeyControllerGet200ResponseAllOf } from './api-key-controller-get200-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { ApiKeyControllerGet200ResponseAllOfItemsInner } from './api-key-controller-get200-response-all-of-items-inner';
// May contain unused imports in some cases
// @ts-ignore
import { Paginated } from './paginated';
// May contain unused imports in some cases
// @ts-ignore
import { PaginatedMeta } from './paginated-meta';

/**
 * @type ApiKeyControllerGet200Response
 * @export
 */
export type ApiKeyControllerGet200Response = ApiKeyControllerGet200ResponseAllOf & Paginated;


