/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChargeStatus } from './charge-status';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface ChargeEntity
 */
export interface ChargeEntity {
    /**
     * 
     * @type {string}
     * @memberof ChargeEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeEntity
     */
    'transactionId': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeEntity
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof ChargeEntity
     */
    'currency': Currency;
    /**
     * 
     * @type {ChargeStatus}
     * @memberof ChargeEntity
     */
    'status': ChargeStatus;
}



