/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PayInStatus } from './pay-in-status';

/**
 * 
 * @export
 * @interface CheckoutTransactionModel
 */
export interface CheckoutTransactionModel {
    /**
     * 
     * @type {string}
     * @memberof CheckoutTransactionModel
     */
    'id': string;
    /**
     * 
     * @type {PayInStatus}
     * @memberof CheckoutTransactionModel
     */
    'status': PayInStatus;
    /**
     * 
     * @type {string}
     * @memberof CheckoutTransactionModel
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutTransactionModel
     */
    'returnUrl'?: string;
}



