/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KYMEntity } from './kymentity';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityBankAccount } from './kymentity-bank-account';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityBusiness } from './kymentity-business';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityCompany } from './kymentity-company';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityContact } from './kymentity-contact';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityPerson } from './kymentity-person';
// May contain unused imports in some cases
// @ts-ignore
import { KYMEntityWebsite } from './kymentity-website';
// May contain unused imports in some cases
// @ts-ignore
import { KYMFlow } from './kymflow';
// May contain unused imports in some cases
// @ts-ignore
import { KYXStatus } from './kyxstatus';
// May contain unused imports in some cases
// @ts-ignore
import { KYXType } from './kyxtype';

/**
 * 
 * @export
 * @interface KYMControllerGet200ResponseAllOfItemsInner
 */
export interface KYMControllerGet200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'accountId': string;
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'name': string;
    /**
     * 
     * @type {KYXType}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'type': KYXType;
    /**
     * 
     * @type {KYXStatus}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'status': KYXStatus;
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'modificationDate': string;
    /**
     * 
     * @type {KYMFlow}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'flow': KYMFlow;
    /**
     * 
     * @type {KYMEntityBusiness}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'business': KYMEntityBusiness;
    /**
     * 
     * @type {KYMEntityContact}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'contact': KYMEntityContact;
    /**
     * 
     * @type {KYMEntityCompany}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'company': KYMEntityCompany;
    /**
     * 
     * @type {Array<KYMEntityPerson>}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'persons': Array<KYMEntityPerson>;
    /**
     * 
     * @type {Array<KYMEntityWebsite>}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'websites': Array<KYMEntityWebsite>;
    /**
     * 
     * @type {KYMEntityBankAccount}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'bankAccount': KYMEntityBankAccount;
    /**
     * 
     * @type {string}
     * @memberof KYMControllerGet200ResponseAllOfItemsInner
     */
    'additionalInformation'?: string;
}



