/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Country } from './country';

/**
 * 
 * @export
 * @interface KYMEntityPerson
 */
export interface KYMEntityPerson {
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'identification': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'dateOfBirth': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'addressLine1': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'addressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'postalCode': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'stateOrCounty': string;
    /**
     * 
     * @type {Country}
     * @memberof KYMEntityPerson
     */
    'country': Country;
    /**
     * 
     * @type {boolean}
     * @memberof KYMEntityPerson
     */
    'isDirector': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KYMEntityPerson
     */
    'isOwner': boolean;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'pictureLegitimation': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityPerson
     */
    'addressLegitimation': string;
}



