/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CompanyOwnershipStructure } from './company-ownership-structure';
// May contain unused imports in some cases
// @ts-ignore
import { Country } from './country';

/**
 * 
 * @export
 * @interface KYMEntityCompany
 */
export interface KYMEntityCompany {
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'registrationNumber': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'addressLine1': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'addressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'postalCode': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'stateOrCounty': string;
    /**
     * 
     * @type {Country}
     * @memberof KYMEntityCompany
     */
    'country': Country;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'email': string;
    /**
     * 
     * @type {CompanyOwnershipStructure}
     * @memberof KYMEntityCompany
     */
    'ownershipStructure': CompanyOwnershipStructure;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityCompany
     */
    'ownershipStructureComment': string;
}



