/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BusinessDeliveryTime } from './business-delivery-time';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface KYMEntityBusiness
 */
export interface KYMEntityBusiness {
    /**
     * 
     * @type {string}
     * @memberof KYMEntityBusiness
     */
    'tradingName': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityBusiness
     */
    'description': string;
    /**
     * 
     * @type {boolean}
     * @memberof KYMEntityBusiness
     */
    'hasRecurringRevenue': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof KYMEntityBusiness
     */
    'hasPhysicalDelivery': boolean;
    /**
     * 
     * @type {BusinessDeliveryTime}
     * @memberof KYMEntityBusiness
     */
    'deliveryTime': BusinessDeliveryTime;
    /**
     * 
     * @type {boolean}
     * @memberof KYMEntityBusiness
     */
    'isDropShipping': boolean;
    /**
     * 
     * @type {Currency}
     * @memberof KYMEntityBusiness
     */
    'currency': Currency;
    /**
     * 
     * @type {number}
     * @memberof KYMEntityBusiness
     */
    'estimateMonthlyTurnover': number;
    /**
     * 
     * @type {number}
     * @memberof KYMEntityBusiness
     */
    'averageTransactionValue': number;
}



