/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountConfigurationType } from './account-configuration-type';

/**
 * 
 * @export
 * @interface MerchantAccountConfigurationEntity
 */
export interface MerchantAccountConfigurationEntity {
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountConfigurationEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountConfigurationEntity
     */
    'accountId': string;
    /**
     * 
     * @type {AccountConfigurationType}
     * @memberof MerchantAccountConfigurationEntity
     */
    'type': AccountConfigurationType;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountConfigurationEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountConfigurationEntity
     */
    'modificationDate': string;
}



