/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OneTimeApiKeyEntity
 */
export interface OneTimeApiKeyEntity {
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'value': string;
    /**
     * 
     * @type {string}
     * @memberof OneTimeApiKeyEntity
     */
    'secret': string;
}

