/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginatedMeta
 */
export interface PaginatedMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMeta
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMeta
     */
    'count': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMeta
     */
    'perPage': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMeta
     */
    'pages': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedMeta
     */
    'page': number;
}

