/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { PayOutFlow } from './pay-out-flow';
// May contain unused imports in some cases
// @ts-ignore
import { PayOutStatus } from './pay-out-status';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionType } from './transaction-type';

/**
 * 
 * @export
 * @interface PayOutEntity
 */
export interface PayOutEntity {
    /**
     * 
     * @type {string}
     * @memberof PayOutEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PayOutEntity
     */
    'accountId': string;
    /**
     * 
     * @type {TransactionType}
     * @memberof PayOutEntity
     */
    'type': TransactionType;
    /**
     * 
     * @type {string}
     * @memberof PayOutEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof PayOutEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof PayOutEntity
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof PayOutEntity
     */
    'currency': Currency;
    /**
     * 
     * @type {PayOutFlow}
     * @memberof PayOutEntity
     */
    'flow': PayOutFlow;
    /**
     * 
     * @type {PayOutStatus}
     * @memberof PayOutEntity
     */
    'status': PayOutStatus;
}



