/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Acquirer } from './acquirer';
// May contain unused imports in some cases
// @ts-ignore
import { AddressModel } from './address-model';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { Gateway } from './gateway';
// May contain unused imports in some cases
// @ts-ignore
import { ItemModel } from './item-model';

/**
 * 
 * @export
 * @interface PayInCardCreateControllerArgs
 */
export interface PayInCardCreateControllerArgs {
    /**
     * 
     * @type {string}
     * @memberof PayInCardCreateControllerArgs
     */
    'accountId': string;
    /**
     * 
     * @type {string}
     * @memberof PayInCardCreateControllerArgs
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof PayInCardCreateControllerArgs
     */
    'currency': Currency;
    /**
     * 
     * @type {Acquirer}
     * @memberof PayInCardCreateControllerArgs
     */
    'acquirer': Acquirer;
    /**
     * 
     * @type {Gateway}
     * @memberof PayInCardCreateControllerArgs
     */
    'gateway': Gateway;
    /**
     * 
     * @type {AddressModel}
     * @memberof PayInCardCreateControllerArgs
     */
    'shippingAddress'?: AddressModel;
    /**
     * 
     * @type {AddressModel}
     * @memberof PayInCardCreateControllerArgs
     */
    'invoiceAddress'?: AddressModel;
    /**
     * 
     * @type {Array<ItemModel>}
     * @memberof PayInCardCreateControllerArgs
     */
    'items'?: Array<ItemModel>;
}



