/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubscriptionRecurControllerArgs
 */
export interface SubscriptionRecurControllerArgs {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionRecurControllerArgs
     */
    'charge'?: boolean;
}

