/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Acquirer } from './acquirer';
// May contain unused imports in some cases
// @ts-ignore
import { AddressModel } from './address-model';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { Gateway } from './gateway';
// May contain unused imports in some cases
// @ts-ignore
import { ItemModel } from './item-model';
// May contain unused imports in some cases
// @ts-ignore
import { PayInFlow } from './pay-in-flow';
// May contain unused imports in some cases
// @ts-ignore
import { PayInStatus } from './pay-in-status';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionType } from './transaction-type';

/**
 * 
 * @export
 * @interface SubscriptionPayInCardEntity
 */
export interface SubscriptionPayInCardEntity {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'accountId': string;
    /**
     * 
     * @type {TransactionType}
     * @memberof SubscriptionPayInCardEntity
     */
    'type': TransactionType;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof SubscriptionPayInCardEntity
     */
    'currency': Currency;
    /**
     * 
     * @type {PayInFlow}
     * @memberof SubscriptionPayInCardEntity
     */
    'flow': PayInFlow;
    /**
     * 
     * @type {PayInStatus}
     * @memberof SubscriptionPayInCardEntity
     */
    'status': PayInStatus;
    /**
     * 
     * @type {Acquirer}
     * @memberof SubscriptionPayInCardEntity
     */
    'acquirer': Acquirer;
    /**
     * 
     * @type {Gateway}
     * @memberof SubscriptionPayInCardEntity
     */
    'gateway': Gateway;
    /**
     * 
     * @type {AddressModel}
     * @memberof SubscriptionPayInCardEntity
     */
    'shippingAddress'?: AddressModel;
    /**
     * 
     * @type {AddressModel}
     * @memberof SubscriptionPayInCardEntity
     */
    'invoiceAddress'?: AddressModel;
    /**
     * 
     * @type {Array<ItemModel>}
     * @memberof SubscriptionPayInCardEntity
     */
    'items'?: Array<ItemModel>;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPayInCardEntity
     */
    'subscriptionId': string;
}



