/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionAuthorizationEntity } from './transaction-authorization-entity';

/**
 * 
 * @export
 * @interface TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
 */
export interface TransactionAuthorizationControllerGet200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'transactionId': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOfItemsInner
     */
    'currency': Currency;
}



