/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TransactionAuthorizationControllerGet200ResponseAllOfItemsInner } from './transaction-authorization-controller-get200-response-all-of-items-inner';

/**
 * 
 * @export
 * @interface TransactionAuthorizationControllerGet200ResponseAllOf
 */
export interface TransactionAuthorizationControllerGet200ResponseAllOf {
    /**
     * 
     * @type {Array<TransactionAuthorizationControllerGet200ResponseAllOfItemsInner>}
     * @memberof TransactionAuthorizationControllerGet200ResponseAllOf
     */
    'items'?: Array<TransactionAuthorizationControllerGet200ResponseAllOfItemsInner>;
}

