/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Paginated } from './paginated';
// May contain unused imports in some cases
// @ts-ignore
import { PaginatedMeta } from './paginated-meta';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionChargeControllerGet200ResponseAllOf } from './transaction-charge-controller-get200-response-all-of';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionChargeControllerGet200ResponseAllOfItemsInner } from './transaction-charge-controller-get200-response-all-of-items-inner';

/**
 * @type TransactionChargeControllerGet200Response
 * @export
 */
export type TransactionChargeControllerGet200Response = Paginated & TransactionChargeControllerGet200ResponseAllOf;


