/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookControllerGet200ResponseAllOfItemsInner } from './webhook-controller-get200-response-all-of-items-inner';

/**
 * 
 * @export
 * @interface WebhookControllerGet200ResponseAllOf
 */
export interface WebhookControllerGet200ResponseAllOf {
    /**
     * 
     * @type {Array<WebhookControllerGet200ResponseAllOfItemsInner>}
     * @memberof WebhookControllerGet200ResponseAllOf
     */
    'items'?: Array<WebhookControllerGet200ResponseAllOfItemsInner>;
}

