/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { WebhookEntity } from './webhook-entity';

/**
 * 
 * @export
 * @interface WebhookControllerGet200ResponseAllOfItemsInner
 */
export interface WebhookControllerGet200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'accountId': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'apiKeyId': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookControllerGet200ResponseAllOfItemsInner
     */
    'modificationDate': string;
}

