/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TransactionChargeControllerGet200Response } from '../model';
// @ts-ignore
import { TransactionChargeEntity } from '../model';
/**
 * TransactionChargesApi - axios parameter creator
 * @export
 */
export const TransactionChargesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionChargeControllerFind: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('transactionChargeControllerFind', 'id', id)
            const localVarPath = `/api/transactions/charges/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} [transactionIds] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionChargeControllerGet: async (transactionIds?: Array<string>, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/transactions/charges`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)

            if (transactionIds) {
                localVarQueryParameter['transactionIds'] = transactionIds;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionChargesApi - functional programming interface
 * @export
 */
export const TransactionChargesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionChargesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionChargeControllerFind(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionChargeEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionChargeControllerFind(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Array<string>} [transactionIds] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionChargeControllerGet(transactionIds?: Array<string>, page?: number, perPage?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionChargeControllerGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionChargeControllerGet(transactionIds, page, perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransactionChargesApi - factory interface
 * @export
 */
export const TransactionChargesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionChargesApiFp(configuration)
    return {
        /**
         * 
         * @param {TransactionChargesApiTransactionChargeControllerFindRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionChargeControllerFind(requestParameters: TransactionChargesApiTransactionChargeControllerFindRequest, options?: AxiosRequestConfig): AxiosPromise<TransactionChargeEntity> {
            return localVarFp.transactionChargeControllerFind(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TransactionChargesApiTransactionChargeControllerGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionChargeControllerGet(requestParameters: TransactionChargesApiTransactionChargeControllerGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<TransactionChargeControllerGet200Response> {
            return localVarFp.transactionChargeControllerGet(requestParameters.transactionIds, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for transactionChargeControllerFind operation in TransactionChargesApi.
 * @export
 * @interface TransactionChargesApiTransactionChargeControllerFindRequest
 */
export interface TransactionChargesApiTransactionChargeControllerFindRequest {
    /**
     * 
     * @type {string}
     * @memberof TransactionChargesApiTransactionChargeControllerFind
     */
    readonly id: string
}

/**
 * Request parameters for transactionChargeControllerGet operation in TransactionChargesApi.
 * @export
 * @interface TransactionChargesApiTransactionChargeControllerGetRequest
 */
export interface TransactionChargesApiTransactionChargeControllerGetRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionChargesApiTransactionChargeControllerGet
     */
    readonly transactionIds?: Array<string>

    /**
     * 
     * @type {number}
     * @memberof TransactionChargesApiTransactionChargeControllerGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof TransactionChargesApiTransactionChargeControllerGet
     */
    readonly perPage?: number
}

/**
 * TransactionChargesApi - object-oriented interface
 * @export
 * @class TransactionChargesApi
 * @extends {BaseAPI}
 */
export class TransactionChargesApi extends BaseAPI {
    /**
     * 
     * @param {TransactionChargesApiTransactionChargeControllerFindRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionChargesApi
     */
    public transactionChargeControllerFind(requestParameters: TransactionChargesApiTransactionChargeControllerFindRequest, options?: AxiosRequestConfig) {
        return TransactionChargesApiFp(this.configuration).transactionChargeControllerFind(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TransactionChargesApiTransactionChargeControllerGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionChargesApi
     */
    public transactionChargeControllerGet(requestParameters: TransactionChargesApiTransactionChargeControllerGetRequest = {}, options?: AxiosRequestConfig) {
        return TransactionChargesApiFp(this.configuration).transactionChargeControllerGet(requestParameters.transactionIds, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }
}
