/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { TransactionAuthorizationControllerGet200Response } from '../model';
// @ts-ignore
import { TransactionAuthorizationEntity } from '../model';
/**
 * TransactionAuthorizationsApi - axios parameter creator
 * @export
 */
export const TransactionAuthorizationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionAuthorizationControllerFind: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('transactionAuthorizationControllerFind', 'id', id)
            const localVarPath = `/api/transactions/authorizations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<string>} [transactionIds] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionAuthorizationControllerGet: async (transactionIds?: Array<string>, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/transactions/authorizations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication API-Key required
            await setApiKeyToObject(localVarHeaderParameter, "API-Key", configuration)

            if (transactionIds) {
                localVarQueryParameter['transactionIds'] = transactionIds;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['perPage'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionAuthorizationsApi - functional programming interface
 * @export
 */
export const TransactionAuthorizationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionAuthorizationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionAuthorizationControllerFind(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionAuthorizationEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionAuthorizationControllerFind(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {Array<string>} [transactionIds] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transactionAuthorizationControllerGet(transactionIds?: Array<string>, page?: number, perPage?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionAuthorizationControllerGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transactionAuthorizationControllerGet(transactionIds, page, perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransactionAuthorizationsApi - factory interface
 * @export
 */
export const TransactionAuthorizationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionAuthorizationsApiFp(configuration)
    return {
        /**
         * 
         * @param {TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionAuthorizationControllerFind(requestParameters: TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest, options?: AxiosRequestConfig): AxiosPromise<TransactionAuthorizationEntity> {
            return localVarFp.transactionAuthorizationControllerFind(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transactionAuthorizationControllerGet(requestParameters: TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<TransactionAuthorizationControllerGet200Response> {
            return localVarFp.transactionAuthorizationControllerGet(requestParameters.transactionIds, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for transactionAuthorizationControllerFind operation in TransactionAuthorizationsApi.
 * @export
 * @interface TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest
 */
export interface TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest {
    /**
     * 
     * @type {string}
     * @memberof TransactionAuthorizationsApiTransactionAuthorizationControllerFind
     */
    readonly id: string
}

/**
 * Request parameters for transactionAuthorizationControllerGet operation in TransactionAuthorizationsApi.
 * @export
 * @interface TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest
 */
export interface TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionAuthorizationsApiTransactionAuthorizationControllerGet
     */
    readonly transactionIds?: Array<string>

    /**
     * 
     * @type {number}
     * @memberof TransactionAuthorizationsApiTransactionAuthorizationControllerGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof TransactionAuthorizationsApiTransactionAuthorizationControllerGet
     */
    readonly perPage?: number
}

/**
 * TransactionAuthorizationsApi - object-oriented interface
 * @export
 * @class TransactionAuthorizationsApi
 * @extends {BaseAPI}
 */
export class TransactionAuthorizationsApi extends BaseAPI {
    /**
     * 
     * @param {TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionAuthorizationsApi
     */
    public transactionAuthorizationControllerFind(requestParameters: TransactionAuthorizationsApiTransactionAuthorizationControllerFindRequest, options?: AxiosRequestConfig) {
        return TransactionAuthorizationsApiFp(this.configuration).transactionAuthorizationControllerFind(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionAuthorizationsApi
     */
    public transactionAuthorizationControllerGet(requestParameters: TransactionAuthorizationsApiTransactionAuthorizationControllerGetRequest = {}, options?: AxiosRequestConfig) {
        return TransactionAuthorizationsApiFp(this.configuration).transactionAuthorizationControllerGet(requestParameters.transactionIds, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }
}
