/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountConfigurationEntity } from './account-configuration-entity';
// May contain unused imports in some cases
// @ts-ignore
import { AccountConfigurationType } from './account-configuration-type';
// May contain unused imports in some cases
// @ts-ignore
import { MerchantAccountConfigurationEntity } from './merchant-account-configuration-entity';

/**
 * @type AccountControllerConfigurations200ResponseInner
 * @export
 */
export type AccountControllerConfigurations200ResponseInner = AccountConfigurationEntity | MerchantAccountConfigurationEntity;


