/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiKeyEntity } from './api-key-entity';

/**
 * 
 * @export
 * @interface ApiKeyControllerGet200ResponseAllOfItemsInner
 */
export interface ApiKeyControllerGet200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyControllerGet200ResponseAllOfItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyControllerGet200ResponseAllOfItemsInner
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyControllerGet200ResponseAllOfItemsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyControllerGet200ResponseAllOfItemsInner
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyControllerGet200ResponseAllOfItemsInner
     */
    'modificationDate': string;
}

