/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum BusinessDeliveryTime {
    LESS_5_DAYS = 'LESS_5_DAYS',
    FROM_5_TO_10_DAYS = 'FROM_5_TO_10_DAYS',
    FROM_10_TO_20_DAYS = 'FROM_10_TO_20_DAYS',
    MORE_20_DAYS = 'MORE_20_DAYS'
}



