/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum CompanyOwnershipStructure {
    SOLE_DIRECTOR = 'SOLE_DIRECTOR',
    SOLE_NOT_DIRECTOR = 'SOLE_NOT_DIRECTOR',
    ONE_OR_MORE_25 = 'ONE_OR_MORE_25',
    NONE_25 = 'NONE_25'
}



