/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KYMControllerGet200ResponseAllOfItemsInner } from './kymcontroller-get200-response-all-of-items-inner';

/**
 * 
 * @export
 * @interface KYMControllerGet200ResponseAllOf
 */
export interface KYMControllerGet200ResponseAllOf {
    /**
     * 
     * @type {Array<KYMControllerGet200ResponseAllOfItemsInner>}
     * @memberof KYMControllerGet200ResponseAllOf
     */
    'items'?: Array<KYMControllerGet200ResponseAllOfItemsInner>;
}

