/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KYXDocumentEntity } from './kyxdocument-entity';
// May contain unused imports in some cases
// @ts-ignore
import { KYXDocumentEntityType } from './kyxdocument-entity-type';
// May contain unused imports in some cases
// @ts-ignore
import { KYXDocumentSide } from './kyxdocument-side';

/**
 * 
 * @export
 * @interface KYMDocumentControllerGet200ResponseAllOfItemsInner
 */
export interface KYMDocumentControllerGet200ResponseAllOfItemsInner {
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'kyxId': string;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'value': string;
    /**
     * 
     * @type {KYXDocumentSide}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'side'?: KYXDocumentSide;
    /**
     * 
     * @type {KYXDocumentEntityType}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'type': KYXDocumentEntityType;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof KYMDocumentControllerGet200ResponseAllOfItemsInner
     */
    'expirationDate'?: string;
}



