/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BankAccountIdentifierType } from './bank-account-identifier-type';
// May contain unused imports in some cases
// @ts-ignore
import { BankAccountSecondIdentifierType } from './bank-account-second-identifier-type';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';

/**
 * 
 * @export
 * @interface KYMEntityBankAccount
 */
export interface KYMEntityBankAccount {
    /**
     * 
     * @type {Currency}
     * @memberof KYMEntityBankAccount
     */
    'currency': Currency;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityBankAccount
     */
    'bankName': string;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityBankAccount
     */
    'identifier': string;
    /**
     * 
     * @type {BankAccountIdentifierType}
     * @memberof KYMEntityBankAccount
     */
    'identifierType': BankAccountIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof KYMEntityBankAccount
     */
    'secondIdentifier': string;
    /**
     * 
     * @type {BankAccountSecondIdentifierType}
     * @memberof KYMEntityBankAccount
     */
    'secondIdentifierType': BankAccountSecondIdentifierType;
}



