/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClearhausPlan } from './clearhaus-plan';
// May contain unused imports in some cases
// @ts-ignore
import { KYMProcessClearhausArgs } from './kymprocess-clearhaus-args';

/**
 * @type KYMProcessControllerArgsAcquirerArgs
 * @export
 */
export type KYMProcessControllerArgsAcquirerArgs = { acquirer: 'CLEARHAUS' } & KYMProcessClearhausArgs;


