/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Acquirer } from './acquirer';
// May contain unused imports in some cases
// @ts-ignore
import { Gateway } from './gateway';
// May contain unused imports in some cases
// @ts-ignore
import { KYMProcessControllerArgsAcquirerArgs } from './kymprocess-controller-args-acquirer-args';

/**
 * 
 * @export
 * @interface KYMProcessControllerArgs
 */
export interface KYMProcessControllerArgs {
    /**
     * 
     * @type {Acquirer}
     * @memberof KYMProcessControllerArgs
     */
    'acquirer': Acquirer;
    /**
     * 
     * @type {Gateway}
     * @memberof KYMProcessControllerArgs
     */
    'gateway': Gateway;
    /**
     * 
     * @type {KYMProcessControllerArgsAcquirerArgs}
     * @memberof KYMProcessControllerArgs
     */
    'acquirerArgs': KYMProcessControllerArgsAcquirerArgs;
}



