/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountType } from './account-type';

/**
 * 
 * @export
 * @interface MerchantAccountEntity
 */
export interface MerchantAccountEntity {
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountEntity
     */
    'userId': string;
    /**
     * 
     * @type {AccountType}
     * @memberof MerchantAccountEntity
     */
    'type': AccountType;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantAccountEntity
     */
    'name': string;
}



