/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaginatedMeta } from './paginated-meta';

/**
 * 
 * @export
 * @interface Paginated
 */
export interface Paginated {
    /**
     * 
     * @type {Array<string>}
     * @memberof Paginated
     */
    'items': Array<string>;
    /**
     * 
     * @type {PaginatedMeta}
     * @memberof Paginated
     */
    'meta': PaginatedMeta;
}

