/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { PayInFlow } from './pay-in-flow';
// May contain unused imports in some cases
// @ts-ignore
import { PayInStatus } from './pay-in-status';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionType } from './transaction-type';

/**
 * 
 * @export
 * @interface PayInEntity
 */
export interface PayInEntity {
    /**
     * 
     * @type {string}
     * @memberof PayInEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PayInEntity
     */
    'accountId': string;
    /**
     * 
     * @type {TransactionType}
     * @memberof PayInEntity
     */
    'type': TransactionType;
    /**
     * 
     * @type {string}
     * @memberof PayInEntity
     */
    'creationDate': string;
    /**
     * 
     * @type {string}
     * @memberof PayInEntity
     */
    'modificationDate': string;
    /**
     * 
     * @type {string}
     * @memberof PayInEntity
     */
    'value': string;
    /**
     * 
     * @type {Currency}
     * @memberof PayInEntity
     */
    'currency': Currency;
    /**
     * 
     * @type {PayInFlow}
     * @memberof PayInEntity
     */
    'flow': PayInFlow;
    /**
     * 
     * @type {PayInStatus}
     * @memberof PayInEntity
     */
    'status': PayInStatus;
}



