/* tslint:disable */
/* eslint-disable */
/**
 * Upnance
 * Upnance API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { KYMDocumentType } from './kymdocument-type';
// May contain unused imports in some cases
// @ts-ignore
import { KYXDocumentSide } from './kyxdocument-side';

/**
 * 
 * @export
 * @interface RequiredKYMDocument
 */
export interface RequiredKYMDocument {
    /**
     * 
     * @type {KYMDocumentType}
     * @memberof RequiredKYMDocument
     */
    'type': KYMDocumentType;
    /**
     * 
     * @type {KYXDocumentSide}
     * @memberof RequiredKYMDocument
     */
    'side'?: KYXDocumentSide;
}



